services:
  api:
    build:
      context: ./backend
    environment:
      - NODE_ENV=production
      - PORT=4000
      - SQLITE_PATH=/data/todos.db
    volumes:
      - ./data:/data
    ports:
      - "4000:4000"

  web:
    build:
      context: ./frontend
      args:
        - VITE_API_BASE=http://localhost:4000
    ports:
      - "8080:80"
    depends_on:
      - api

volumes:
  dbdata:
